name: Playwright Tests
on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1.Cloning the App
      - name: Clone and Install App
        run: |
          if [ ! -d "app" ]; then
            git clone https://github.com/cypress-io/cypress-realworld-app.git app
          fi
          cd app
          yarn install --frozen-lockfile

      # 2. Install Playwright Framework
      - name: Install Playwright Framework
        run: |
          npm install
          npx playwright install --with-deps

      # 3. Building the App and Running Tests
      - name: Run Playwright tests
        run: |
          cd app && yarn dev &
          npx wait-on http://localhost:3000 http://localhost:3001 --timeout 180000
          npx playwright test
        env:
          TESTUSER: ${{ secrets.TESTUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      # 4. Uploading the Report
      - name: Fix Jekyll for Pages
        if: always()
        run: touch playwright-report/.nojekyll

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: playwright-report/

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4
