name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "./app/yarn.lock"

      # 1. Install App dependencies
      - name: Install Application
        working-directory: ./app
        run: yarn install --frozen-lockfile

      # 2. Install Test Framework dependencies
      - name: Install Playwright Framework
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 3. Start App & Run Tests
      - name: Run Playwright tests
        run: |
          cd app && yarn dev &
          npx wait-on http://localhost:3000 --timeout 120000
          npx playwright test
        env:
          TESTUSER: ${{ secrets.TESTUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      # 4. Save Report
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
